# Generated by Django 4.0.4 on 2022-04-19 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='semesters.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='wieght',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
