# Generated by Django 4.0.4 on 2022-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterias', '0001_initial'),
        ('projects', '0002_project_semester_project_wieght'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='criteria',
            field=models.ManyToManyField(to='criterias.criteria'),
        ),
    ]
